feat: added buildAuthorizeUrl and buildLogoutUrl from auth0-spa-js
auth0/auth0-react pull request #190
Opened 2021-01-30 03:27 UTC by THISS

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Added in the buildAuthorizeUrl and buildLogoutUrl which were both in the https://github.com/auth0/auth0-spa-js repo. This helps with projects that need more management over the browser client eg. Ionic using capacitor requires a native "Browser" plugin to do redirects in app.

### References

Related PRs from the spa-js repo: https://github.com/auth0/auth0-spa-js/pull/280, https://github.com/auth0/auth0-spa-js/pull/595

### Testing

Added to the `auth-provider.test.tsx` unit tests a couple of noop tests for coverage that just make sure the call is passed through to the Auth0Client similar to a couple of other tests. I looked at cypress but it seems there is just a bare bones smoke test so didn't feel this needed the full treatment of getting the strings. Let me know if you would like them added

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

2021-02-04 15:19 UTC, adamjmcgrath requested changes

2021-02-04 15:19 UTC, adamjmcgrath commented on src/auth0-provider.tsx
> +    (opts?: Auth0RedirectLoginOptions): Promise<string> =>
```js
const buildAuthorizeUrl = useCallback(
  (opts?: RedirectLoginOptions): Promise<string> =>
    client.buildAuthorizeUrl(toAuth0LoginRedirectOptions(opts)),
  [client]
);
```

(this SDK uses `redirectUri` and spa-js uses `redirect_uri`)

2021-02-04 15:19 UTC, adamjmcgrath commented on src/auth0-provider.tsx
> +  LogoutUrlOptions,
Can you export this from https://github.com/auth0/auth0-react/blob/master/src/index.tsx#L17-L26

2021-02-10 06:23 UTC, THISS commented on src/auth0-provider.tsx
> +    (opts?: Auth0RedirectLoginOptions): Promise<string> =>
ah, good catch 👍 thanks for that man

2021-02-10 06:23 UTC, THISS commented on src/auth0-provider.tsx
> +  LogoutUrlOptions,
apologies on the delay between me seeing this and your review.

2021-02-10 14:10 UTC, adamjmcgrath commented on src/auth0-provider.tsx
> +      client.buildAuthorizeUrl(opts),
Annoyingly you still need to do `client.buildAuthorizeUrl(toAuth0LoginRedirectOptions(opts))`

Somewhere in between making spa js and auth0-react we changed the options from snake case to camel case

2021-02-10 16:04 UTC, THISS commented on src/auth0-provider.tsx
> +      client.buildAuthorizeUrl(opts),
sorry about that, I had checked how it is converted but forgot to add in the method that converts it...

2021-02-10 16:26 UTC, adamjmcgrath approved these changes

2021-02-10 16:26 UTC, merged

2021-02-10 16:26 UTC, adamjmcgrath commented
Thanks @THISS!

2021-02-11 08:56 UTC, aaronadamsCA commented
I was literally just opening a feature request to expose the logout URL, and I was growing increasingly confused why I could see this capability on GitHub, but not in my IDE. Imagine my surprise that it was added within the last 24 hours.

Thanks for this! Putting it to use already in a Shopify app, which runs inside an iframe and therefore can't just call `logout()`. 🙌

2021-02-16 18:06 UTC, adamjmcgrath commented
Release in https://github.com/auth0/auth0-react/releases/tag/v1.3.0