feat: Add popup option to `withAuthenticationRequired`
auth0/auth0-react pull request #195
Opened 2021-02-05 16:50 UTC by Vivalldi

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Gives users the option to Auth with a Popup in wrapped components. This is driven by the need for an app to function inside an iframe.

Added a `popup` option to `withAuthenticationRequired` option dictionary. It defaults to `false`. The login method is then chosen based on the value of `popup`.

### References

- Closes #166 

### Testing

Test by setting `popup` to `true` when wrapping a component.

Developed in TS on macOS 10.15.7 in Chrome 88

- [x] This change adds test coverage for new/changed/fixed functionality

Not entirely sure why my test isn't passing

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

2021-02-05 16:53 UTC, Vivalldi commented on __tests__/with-authentication-required.test.tsx
> +    await waitFor(() => expect(mockClient.loginWithPopup).toHaveBeenCalled());
This line doesn't resolve within 5 seconds. I'm not entirely sure how to resolve this.

2021-02-05 17:43 UTC, adamjmcgrath commented on __tests__/with-authentication-required.test.tsx
> +    await waitFor(() => expect(mockClient.loginWithPopup).toHaveBeenCalled());
This is to be expected, because you're not logging in the user `mockClient.getUser.mockResolvedValue` always returns undefined.

If you protected a route with `loginWithPopup` but it resolves without the user logging in, `withAuthenticationRequired` would just pop the login up again until you login.

You should be able to fix this by  mocking the user value as falsey on the first call, then a valid user object on the second, eg:

```js
mockClient.getUser.mockResolvedValueOnce(undefined);
mockClient.getUser.mockResolvedValueOnce({ name: '__test_user__' });
```

2021-02-05 17:45 UTC, adamjmcgrath commented on src/with-authentication-required.tsx
>    loginOptions?: RedirectLoginOptions;
This will also be `PopupLoginOptions` and you'll need to implement `PopupConfigOptions`

2021-02-05 18:55 UTC, adamjmcgrath requested changes
looks good, a couple of changes requested

2021-04-16 12:53 UTC, adamjmcgrath commented
@Vivalldi - closing due to inactivity. Happy to reopen if you want to finish this off

2021-04-16 12:53 UTC, closed without merging