Add ability to check JWT claims
auth0/auth0-react pull request #211
Opened 2021-03-13 03:34 UTC by ctjlewis

### Description
I wanted to easily protect a route not only for valid users, but also for those with a given `ROLE` JWT claim. I figured I'd send this PR in for review in case this team was interested in merging the changes, or some version of them.

### Testing
Unit tests were added to ensure that protected routes only showed to users with all specified JWT claims. If no `requiredClaims` are provided in `WithAuthenticationRequiredOptions`, the claims check automatically passes.

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

2021-03-13 05:35 UTC, ctjlewis commented
In trying to link this package and use it, I get the following error but can't figure out why (I'm sure it's something simple):

![image](https://user-images.githubusercontent.com/1657236/111020450-8e897d00-838b-11eb-81fd-e46be7c8ca4b.png)

2021-03-15 07:33 UTC, ctjlewis commented
Requesting notes from: @adamjmcgrath, @Vivalldi (sorry to ping)

2021-03-15 11:20 UTC, adamjmcgrath commented
Hi @ctjlewis - thanks for raising this PR, checking claims to access routes would be a great addition to the SDK.

I have a request about the implementation - could you change it to accepting function that returns a boolean to indicate if the claim check passes, eg

> Example of an unauthorized route request. User with ['USER', 'MODERATOR'] claim trying to access a protected component that is only for ROLE claims that include 'ADMIN':

```js
const WrappedComponent = withAuthenticationRequired(MyComponent, {
  claimCheck(claims) {
    return claims['https://my.app.io/jwt/claims'].includes('ADMIN')
  }
}); 
```

(The name `claimCheck` is consistent with some of our [other](https://auth0.github.io/express-openid-connect/globals.html#claimcheck) js APIs)

2021-03-15 15:32 UTC, adamjmcgrath commented
@ctjlewis 

> In trying to link this package and use it, I get the following error but can't figure out why (I'm sure it's something simple):

It's a pain to link packages that use react hooks - you could try pointing `react` and `react-dom` to `../auth0-react/node_modules/react` and `../auth0-react/node_modules/react-dom`. 

Or just try using `npm pack` and installing the tar file locally

2021-03-16 04:47 UTC, ctjlewis commented
That made the code change much smaller and more straightforward, probably the best approach. Please lmk what you think about the changes.

2021-03-16 09:35 UTC, adamjmcgrath requested changes
looks good - couple of suggestions

2021-03-16 09:35 UTC, adamjmcgrath commented on src/with-authentication-required.tsx
> +  [claim: string]: string | string[];
These can be bools, numbers, arrays of mixed types, objects etc...

Just use [User](https://github.com/auth0/auth0-react/blob/master/src/auth-state.tsx#L1) for the type passed into `claimCheck` (I have a backlog item to improve that type)

`claimCheck?: (user: User) => boolean;`

2021-03-16 09:35 UTC, adamjmcgrath commented on src/with-authentication-required.tsx
> +    const routeIsAuthenticated = isAuthenticated && claimsAreAuthenticated;
Let's only run `claimCheck` when the user is logged in.

`const routeIsAuthenticated = isAuthenticated && claimCheck(user);`

2021-03-16 09:39 UTC, adamjmcgrath commented on src/with-authentication-required.tsx
> +    const routeIsAuthenticated = isAuthenticated && claimsAreAuthenticated;
Then you can cast it as `User` and you don't need the default on line 92

`const routeIsAuthenticated = isAuthenticated && claimCheck(user as User);`

2021-03-16 10:26 UTC, ctjlewis commented on src/with-authentication-required.tsx
> +  [claim: string]: string | string[];
It would complain right now when we try to index with a claim like `user['http://app.io']`, wouldn't it? We just need to add an index type like `[jwtClaim: string]: string | string[]` since the claims are stored directly on the user object.

2021-03-16 12:24 UTC, adamjmcgrath commented on src/with-authentication-required.tsx
> +  [claim: string]: string | string[];
For example, it's [common to add roles](https://auth0.com/docs/authorization/sample-use-cases-rules-with-authorization#add-user-roles-to-tokens) like `user['http://app.io/roles']: ['USER', 'MODERATOR']`

So this test should pass:

```js
  it('should not allow access to claims-restricted components', async () => {
    const claimCheck = (claims: JWTNamespaces) =>
      claims['https://my.app.io/jwt/admin']?.includes('ADMIN');
    const MyComponent = (): JSX.Element => <>Private</>;
    const WrappedComponent = withAuthenticationRequired(MyComponent, {
      claimCheck,
    });
    /**
     * A user with USER and MODERATOR roles.
     */
    const mockUser = {
      name: '__test_user__',
      'https://my.app.io/jwt/roles': ['USER', 'MODERATOR'],
    };
    mockClient.getUser.mockResolvedValue(mockUser);

    render(
      <Auth0Provider clientId="__test_client_id__" domain="__test_domain__">
        <WrappedComponent />
      </Auth0Provider>
    );
    await waitFor(() =>
      expect(mockClient.loginWithRedirect).toHaveBeenCalled()
    );
    expect(screen.queryByText('Private')).not.toBeInTheDocument();
  });
```

But I get the TypeScript error `TS2349: This expression is not callable.   No constituent of type 'string | string[]' is callable.`

But if I chnage the signature of `claimCheck` to `(claims: User)` it passes

2021-03-25 03:40 UTC, ctjlewis commented
Though this assumes JWT claims will be `string | string[]`, I think it's a good place to start. I would appreciate any help regarding docs or adding support for types outside of strings or arrays of strings.

2021-03-25 07:47 UTC, adamjmcgrath commented
Hi @ctjlewis 

If you change the [signature of claimCheck](https://github.com/auth0/auth0-react/pull/211/files#diff-9beee0b2de625b72236426c61a1798f8dd1cedee94b410584ba90b1b241a18abR75) to accept a [User](https://github.com/auth0/auth0-react/blob/master/src/auth-state.tsx#L1) I'd be happy to proceed with this PR

2021-03-25 08:43 UTC, ctjlewis commented
Please let me know if these changes are sufficient.

2021-03-25 08:57 UTC, adamjmcgrath commented on src/with-authentication-required.tsx
> +  claimCheck?: (claims: JWTNamespaces | User) => boolean;
```suggestion
  claimCheck?: (claims: User) => boolean;
```
And please could you delete the `JWTClaim` and `JWTNamespaces` types

2021-03-25 10:05 UTC, adamjmcgrath commented
@ctjlewis - couple of other things

The dependent key for the `useEffect` should be `routeIsAuthenticated` not `isAuthenticated`
And we only want to run the `claimCheck` function if the user is authenticated.

I've made the changes and put them here for your reference https://github.com/auth0/auth0-react/commit/3a8514d0f49673a1c862640c86eaeb10c2a1044a

2021-03-26 02:22 UTC, ctjlewis commented
Thank you very much for your help on this Adam. I merged your suggestions.

2021-03-26 09:45 UTC, adamjmcgrath commented
Hey @ctjlewis 

It doesn't look like you implemented the majority of changes I suggested in 3a8514d - could you take another look

Also - could you revert your changes to `with-auth.tsx`?

2021-03-29 00:28 UTC, ctjlewis commented
The changes in `with-auth0.tsx` were just to silence the following tsc error:

```none
'auth0' is specified more than once, so this usage will be overwritten.ts(2783)
```

2021-03-29 07:44 UTC, adamjmcgrath commented
> The changes in with-auth0.tsx were just to silence the following tsc error

Am not seeing that error on [the CI server](https://circleci.com/gh/auth0/auth0-react/416?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) - perhaps you're using a different TS compiler than the project.

2021-03-29 07:45 UTC, adamjmcgrath approved these changes
lgtm - thanks @ctjlewis!

2021-03-29 07:45 UTC, merged