Update SPA JS, TS and add orgs example
auth0/auth0-react pull request #220
Opened 2021-03-23 15:30 UTC by adamjmcgrath

### Description

- Update SPA JS
- Make sure SPA JS organization docs appear in auth0-react docs (update TS and tsdoc)
- Add an organizations example

### References

![image](https://user-images.githubusercontent.com/1299658/112172364-8f70a900-8bec-11eb-8fc3-09fcc3302cdc.png)

2021-03-23 15:31 UTC, adamjmcgrath commented on src/auth0-context.tsx
> +export interface RedirectLoginOptions
The new version of tsdoc is better at surfacing inherited types

2021-03-23 15:32 UTC, adamjmcgrath commented on src/with-auth0.tsx
> +      <Component {...(props as P)} auth0={auth} />
The new version of TS was grumbling at the order of these props

2021-03-23 15:41 UTC, frederikprijck requested changes

2021-03-23 15:41 UTC, frederikprijck commented on EXAMPLES.md
> +## 5. Accept a user invite and login to an organization
Should we have guidance around logging in to an org without accepting a user invitation? I think both SPAJS and Angular SDK treat these separately from one another.

2021-03-23 15:41 UTC, frederikprijck commented on src/auth0-provider.tsx
> +  extends Exclude<Auth0ClientOptions, 'client_id' | 'redirect_uri'> {
TIL about Exclude<...> 😱

2021-03-23 15:58 UTC, adamjmcgrath commented
Just gonna close while I investigate these test failures

2021-03-23 15:58 UTC, closed without merging

2021-03-24 09:49 UTC, adamjmcgrath commented
Reverted the TS updates (need to wait for TS 3.9)

2021-03-24 09:51 UTC, adamjmcgrath commented on EXAMPLES.md
> +## 5. Accept a user invite and login to an organization
GH wouldn't let me ropen this one - have raised a new one at #221 

> Should we have guidance around logging in to an org without accepting a user invitation?

Have added some more comments around the `organization` init argument - I'd like to keep all the guidance in one example