Add TUser type param to useAuth0 hook
auth0/auth0-react pull request #230
Opened 2021-04-15 11:13 UTC by Jameskmonger

### Description

Adds generic type parameter to `useAuth0` to specify type of `user` (see #228 for feature request)

```ts
const { user } = useAuth0<{ name: string; }>();

user.name // string
```

### References

Closes #228 

### Testing

I tried to unit test this but I'm not sure of the correct way to pass type params to a hook through `renderHook`

You can see this in-use in the Create React App example

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

2021-04-15 12:16 UTC, adamjmcgrath requested changes
lgtm

2021-04-15 12:16 UTC, adamjmcgrath commented on README.md
> +  } = useAuth0<{ name: string }>();
```suggestion
  } = useAuth0();
```

The README examples are plain js

2021-04-15 12:16 UTC, adamjmcgrath commented
fixes #201

2021-04-16 07:52 UTC, adamjmcgrath approved these changes

2021-04-16 07:52 UTC, merged

2021-04-16 07:52 UTC, adamjmcgrath commented
Thanks @Jameskmonger!

2021-04-16 08:35 UTC, Jameskmonger commented
Thanks for merging @adamjmcgrath 😄