[SDK-2603] Expose custom caching options from Auth0 SPA SDK
auth0/auth0-react pull request #255
Opened 2021-07-05 16:07 UTC by stevehobbsdev

### Description

This PR upgrades `@auth0/auth0-spa-js` to [v1.16.0](https://github.com/auth0/auth0-spa-js/releases/tag/v1.16.0) and exposes the new custom cache option.

### References

https://github.com/auth0/auth0-spa-js/releases/tag/v1.16.0
https://github.com/auth0/auth0-spa-js/pull/743

### Testing

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

2021-07-06 08:53 UTC, adamjmcgrath approved these changes

2021-07-07 19:31 UTC, stevehobbsdev commented on __tests__/auth-provider.test.tsx
> +    await waitForNextUpdate();
@adamjmcgrath Can you confirm if this is the way to handle this in the test? As the logout function is now async, I concluded that we'd need to wait until the next tick before asserting (it fails without this line).

2021-07-08 08:54 UTC, adamjmcgrath commented on __tests__/auth-provider.test.tsx
> +    await waitForNextUpdate();
@stevehobbsdev `logout` needs to remain sync by default here as well - I added c8742512a6da7244da50902f05bcf9cea91dd314

2021-07-08 08:56 UTC, adamjmcgrath approved these changes

2021-07-08 09:00 UTC, adamjmcgrath requested changes
need to return the promise from logout

2021-07-08 09:14 UTC, adamjmcgrath submitted a review, later dismissed

2021-07-08 09:34 UTC, adamjmcgrath approved these changes

2021-07-08 11:15 UTC, stevehobbsdev commented on __tests__/auth-provider.test.tsx
> +    await waitForNextUpdate();
Thanks for taking care of it 👍🏻

2021-07-14 09:51 UTC, merged

2021-07-14 10:07 UTC, benhunterandrewrobertson commented
Awesome work guys, been holding out for this one. Much appreciated!