Avoid potential multiple invocations of loginWithRedirect
auth0/auth0-react pull request #311
Opened 2021-12-22 13:41 UTC by kweiberth

Resolves https://github.com/auth0/auth0-react/issues/309

2021-12-22 14:37 UTC, adamjmcgrath requested changes

2021-12-22 14:37 UTC, adamjmcgrath commented on src/with-authentication-required.tsx
> +      // We used to default to empty object here w/ `loginOptions = {}`, but
Could you remove this comment and instead add a regression test to [with-authentication-required.test.tsx](https://github.com/auth0/auth0-react/blob/master/__tests__/with-authentication-required.test.tsx)

Something like:

```js
it('should only call login once when parent state changes', async () => {
    mockClient.getUser.mockResolvedValue(undefined);
    const MyComponent = (): JSX.Element => <>Private</>;
    const WrappedComponent = withAuthenticationRequired(MyComponent);
    const App = ({ foo }: { foo: number }): JSX.Element => (
      <div>
        {foo}
        <Auth0Provider clientId="__test_client_id__" domain="__test_domain__">
          <WrappedComponent />
        </Auth0Provider>
      </div>
    );
    const { rerender } = render(<App foo={1} />);
    await waitFor(() =>
      expect(mockClient.loginWithRedirect).toHaveBeenCalled()
    );
    mockClient.loginWithRedirect.mockClear();
    rerender(<App foo={2} />);
    await waitFor(() =>
      expect(mockClient.loginWithRedirect).not.toHaveBeenCalled()
    );
  });
```

2021-12-23 12:32 UTC, adamjmcgrath approved these changes

2021-12-23 12:32 UTC, adamjmcgrath commented
Thanks @kweiberth! Will do put up a release straight after the holidays

2021-12-23 12:41 UTC, merged

2021-12-23 12:49 UTC, kweiberth commented
Thank you @adamjmcgrath! And thanks for writing out the test. All sounds good, happy holidays!

2022-04-11 00:11 UTC, kevin19940627 commented
Hi there, withAuthenticationRequired seems to be invoking login multiple times with React 18 create react app. issues seem to appear when we use the new createRoot() API. is anyone experiencing the same issue?