[SDK-4436] test: Migrate CI to GitHub Actions
auth0/auth0-react pull request #564
Opened 2023-08-29 05:20 UTC by evansims

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

This pull request replaces our current CircleCI continuous integration suite for `auth0-react` with a new workflow using GitHub Actions.

### References

Please see internal ticket SDK-4436.

### Testing

This pull request replaces our continuous integration suite with one built in GitHub's native Actions ecosystem. It aligns with other migrations taking place across our repositories.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not the default branch

2023-08-29 05:31 UTC, evansims commented
Note that the existing "Code scanning results / CodeQL" may not pass as this pull request replaces it's YAML configuration; we'll force-merge after approval.

2023-08-29 08:04 UTC, frederikprijck requested changes

2023-08-29 08:04 UTC, frederikprijck commented on .github/workflows/publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
What's the benefit of uploading this to GitHub?

2023-08-29 08:04 UTC, frederikprijck commented on .github/workflows/test.yml
> +    name: BrowserSTack Tests
```suggestion
    name: BrowserStack Tests
```

2023-08-29 08:04 UTC, frederikprijck commented on .github/workflows/test.yml
> +  integration:
Would it make sense to split this like we did with Auth0-SPA-JS to simplify making changes to the main workflow file to compile the SDK?

2023-08-29 08:34 UTC, frederikprijck commented on .github/workflows/publish.yml
> +      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
I'm not sure GitHub actions works the same like circle, where every branch (master and beta) has its own workflow copy with small changes.

If not, I can understand why we need the above, but we need to ensure we account for that below when running npm publish. If we do not do that, I would opt to, for the time being, remove the beta tag triggers. (either by removing the above two beta references, or by using `release type released`.

2023-08-29 18:04 UTC, evansims commented on .github/actions/build/action.yml
> +      run: npm ci --include=dev
Just a fail-safe in case `NODE_ENV` happens to be changed elsewhere in a parent job invoking the action. `--include=dev` forces development dependencies to be installed, even if NODE_ENV is set to `production.` Not necessarily needed, but I thought it safer to err on the side of caution and include it.

2023-08-29 18:06 UTC, evansims commented on .github/workflows/publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Enables the package to be distributed via [GitHub Packages](https://github.com/features/packages) (an alternative to NPM's own registry), for customers who might desire it. Thought it was worth enabling support for it, but I'm fine with removing it if you feel otherwise.

2023-08-29 18:15 UTC, evansims commented on .github/workflows/publish.yml
> +      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
Discussed during office hours call today; doing some research on a better approach to this presently.

2023-08-29 18:30 UTC, evansims commented on .github/workflows/publish.yml
> +          key: ${{ env.CACHE_KEY }}
Good call! Never heard of that lifecycle situation — neat! I'll remove the job in that case.

Guessing dependencies aren't automatically installed as part of that lifecycle, as far as I'm able to find in the documentation? Assuming that's the case I'll add a dependency install step for now, unless you say otherwise.

2023-08-29 21:58 UTC, frederikprijck commented on .github/workflows/publish.yml
> +          key: ${{ env.CACHE_KEY }}
Correct, only does the build, so we need npm install/ci

2023-08-29 22:00 UTC, frederikprijck commented on .github/workflows/publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Im not against it at all, was mostly unfamiliar and curious how someone might use it.

2023-08-29 22:03 UTC, frederikprijck commented on .github/workflows/test.yml
> +  integration:
I don't think we collect coverage from our integration tests, so not sure what you mean exactly.

I was only referring to the integration tests, the unit tests should stay here for sure.

2023-08-29 22:59 UTC, evansims commented on .github/workflows/test.yml
> +  integration:
Not integration tests, the Jest unit tests. Jest is invoked with the `--coverage` flag, and produces the coverage files codecov requires.

2023-08-29 22:59 UTC, evansims commented on .github/workflows/publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Gotcha, OK

2023-09-05 07:38 UTC, frederikprijck commented on .github/workflows/test.yml
> +  integration:
Yeah, I was referring to the same as being done [here](https://github.com/auth0/auth0-spa-js/pull/1126). Happy to do that in a follow up PR if u prefer, but that would keep the main CI workflow a bit simpler in terms of updating it and ensuring the updates work correctly prior to merging.

2023-09-07 04:35 UTC, evansims commented on .github/workflows/publish.yml
> +      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
Updated to use the new manually triggered workflow we discussed, based on auth0.js' migration

2023-09-08 06:51 UTC, merged